# Generated by Django 2.2 on 2019-04-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=15)),
                ('timestamp', models.BigIntegerField()),
                ('accuracy', models.IntegerField()),
                ('data', models.CharField(max_length=16)),
                ('device', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Participant')),
            ],
        ),
    ]
